### ISSUE TITLE
Error 503 Backend fetch failed

### ISSUE THREAD

**Issue by tengpaper** [TreeCmp/TreeCmpWEB#1]
Hello!  I want to use the online Visual TreeCmp, but just find that the website https://eti.pg.edu.pl/TreeCmp/WEB can not be opened, and the error  is as follow:

Error 503 Backend fetch failed
Backend fetch failed

Guru Meditation:
XID: 289818383

Varnish cache server

Wish your reply.

**Comment by goluch** [comment]
The reason was a problem with the power supply, it's already ok.
